FROM ubuntu:wily
MAINTAINER agw.lvs.sainokuni@gmail.com
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install curl unzip
RUN apt-get -y install build-essential
RUN apt-get -y install git git-flow
RUN apt-get -y autoremove
RUN apt-get -y autoclean
